/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.AlumnosControlador;
import Controlador.CatalogosControlador;
import Controlador.ReportesControlador;
import Exceptions.ControlEscolarException;
import Modelo.Alumnos;
import Modelo.Grupos;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author cgarcia
 */
public class FormReporteCalificaciones extends FormBase {
    
    private AlumnosControlador alumnosControlador;
    private CatalogosControlador catalogosControlador;
    private ReportesControlador reportes;

    /**
     * Creates new form FormReporteCalificaciones
     */
    public FormReporteCalificaciones() {
        initComponents();
        alumnosControlador = new AlumnosControlador();
        catalogosControlador = new CatalogosControlador();
        reportes = new ReportesControlador();
        
        List<String> grupos = catalogosControlador.consultaGrupos();
        cboGrupo.setModel(new DefaultComboBoxModel(grupos.toArray()));
        
        List<String> als = alumnosControlador.consultaNombreAlumnos(getIdGrupo());
        cboAlumnos.setModel(new DefaultComboBoxModel(als.toArray()));
    }
    
    private int getIdGrupo() {
        Grupos gpo = catalogosControlador.consultaGrupo(cboGrupo.getSelectedItem().toString());
        return gpo != null && gpo.getIdGrupo() != null ? gpo.getIdGrupo() : 0;
    }
    
    private int getIdAlumno() {
        String al = cboAlumnos.getSelectedItem().toString();
        String[] datos = al.split("-");
        return Integer.parseInt(datos[0].trim());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboGrupo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cboAlumnos = new javax.swing.JComboBox<>();
        btnExportar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("REPORTE CALIFICACIONES");

        jLabel1.setText("GRUPO");

        cboGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 A", "1 B", "1 C" }));
        cboGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarAlumnos(evt);
            }
        });

        jLabel2.setText("ALUMNO");

        btnExportar.setText("Exportar");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportarReporte(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnExportar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cboAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCancelar)
                    .addComponent(btnExportar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarAlumnos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarAlumnos
        List<String> als = alumnosControlador.consultaNombreAlumnos(getIdGrupo());
        cboAlumnos.setModel(new DefaultComboBoxModel(als != null && !als.isEmpty() ? als.toArray() : new String[0]));
    }//GEN-LAST:event_cargarAlumnos

    private void exportarReporte(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportarReporte
        Alumnos al = alumnosControlador.getById(getIdAlumno());
        try {
            reportes.exportarCalificaciones(al);
        } catch (ControlEscolarException ex) {
            agregarMensajeError(ex.getMessage());
        }
    }//GEN-LAST:event_exportarReporte


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExportar;
    private javax.swing.JComboBox<String> cboAlumnos;
    private javax.swing.JComboBox<String> cboGrupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
