/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.AlumnosControlador;
import Controlador.CardexControlador;
import Controlador.CatalogosControlador;
import Controlador.MateriasControlador;
import Exceptions.ControlEscolarException;
import Modelo.Alumnos;
import Modelo.Cardex;
import Modelo.Grupos;
import Modelo.Materias;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cgarcia
 */
public class FormAlumnosCardex extends FormBase {

    private AlumnosControlador alumnosControlador;
    private CatalogosControlador catalogosControlador;
    private MateriasControlador materiasControlador;
    private CardexControlador cardexControlador;
    
    /**
     * Creates new form FormAlumnosCardex
     */
    public FormAlumnosCardex() {
        initComponents();
        alumnosControlador = new AlumnosControlador();
        catalogosControlador = new CatalogosControlador();
        materiasControlador = new MateriasControlador();
        cardexControlador = new CardexControlador();
        
        List<String> grupos = catalogosControlador.consultaGrupos();
        cboGrupo.setModel(new DefaultComboBoxModel(grupos.toArray()));
        
        List<String> als = alumnosControlador.consultaNombreAlumnos(getIdGrupo());
        cboAlumnos.setModel(new DefaultComboBoxModel(als.toArray()));
            
    }
    
    private void limpiarTabla() {
        DefaultTableModel model = (DefaultTableModel) tblResultados.getModel();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
    }
    
    private int getIdGrupo() {
        Grupos gpo = catalogosControlador.consultaGrupo(cboGrupo.getSelectedItem().toString());
        return gpo != null && gpo.getIdGrupo() != null ? gpo.getIdGrupo() : 0;
    }
    
    private int getIdAlumno() {
        String al = cboAlumnos.getSelectedItem().toString();
        String[] datos = al.split("-");
        return Integer.parseInt(datos[0].trim());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboGrupo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cboAlumnos = new javax.swing.JComboBox<>();
        btnAbrir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultados = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("CARDEX");

        jLabel1.setText("GRUPO");

        cboGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 A", "1B", "1C" }));
        cboGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaAlumno(evt);
            }
        });

        jLabel2.setText("ALUMNO");

        btnAbrir.setText("Abrir");
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarCardex(evt);
            }
        });

        tblResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Materia", "P1", "P2", "P3", "OR", "EX", "TI"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblResultados);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarCardex(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarCalificaciones(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboAlumnos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAbrir))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cboAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAbrir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarCardex(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarCardex
        this.dispose();
    }//GEN-LAST:event_cancelarCardex

    private void guardarCalificaciones(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarCalificaciones
        DefaultTableModel model = (DefaultTableModel) tblResultados.getModel();
        int idAlumno = getIdAlumno();
        boolean error = false;
        if (model.getRowCount() > 0) {
            for (int i = 0; i < model.getRowCount(); i++) {
                Cardex c = new Cardex();
                c.setIdAlumno(idAlumno);
                c.setIdMateria((Integer) model.getValueAt(i, 0));
                c.setParcial1((Float) model.getValueAt(i, 2));
                c.setParcial2((Float) model.getValueAt(i, 3));
                c.setParcial3((Float) model.getValueAt(i, 4));
                c.setOrdinario((Float) model.getValueAt(i, 5));
                c.setExtraordinario((Float) model.getValueAt(i, 6));
                c.setTitulo((Float) model.getValueAt(i, 7));
                if (cardexValido(c)) {
                    try {
                        cardexControlador.actualizarCardex(c);
                    } catch (ControlEscolarException ex) {
                        agregarMensajeError(ex.getMessage());
                        error = true;
                        break;
                    }
                } else {
                    agregarMensajeError("Las calificaciones no debe ser mayor a 10");
                    error = true;
                    break;
                }
            }
        }
        if (!error) {
            agregarMensajeExito("Se guardaron correctamente las calificaciones");
        }
    }//GEN-LAST:event_guardarCalificaciones

    private boolean cardexValido(Cardex c) {
        boolean valido = true;
        if (c.getParcial1() != null && c.getParcial1() > 10) {
            valido = false;
        }
        if (c.getParcial2() != null && c.getParcial2() > 10) {
            valido = false;
        }
        if (c.getParcial3() != null && c.getParcial3() > 10) {
            valido = false;
        }
        if (c.getOrdinario() != null && c.getOrdinario() > 10) {
            valido = false;
        }
        if (c.getExtraordinario() != null && c.getExtraordinario() > 10) {
            valido = false;
        }
        if (c.getTitulo() != null && c.getTitulo() > 10) {
            valido = false;
        }
        return valido;
    }
    private void cargarCardex(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarCardex
        Alumnos al = alumnosControlador.getById(getIdAlumno());
        List<Materias> materias = materiasControlador.consultarMateriasSemestre(
                Integer.parseInt(al.getGrupo().getSemestre()));
        limpiarTabla();
        DefaultTableModel model = (DefaultTableModel) tblResultados.getModel();
        for (Materias mat : materias) {
            Cardex cardex = cardexControlador.consultaCardex(al.getIdAlumno(), mat);
            model.addRow(new Object[]{cardex.getIdMateria(), cardex.getNombreMateria(),
                    cardex.getParcial1(), cardex.getParcial2(), cardex.getParcial3(), 
                    cardex.getOrdinario(), cardex.getExtraordinario(), cardex.getTitulo()});
        }
    }//GEN-LAST:event_cargarCardex

    private void consultaAlumno(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaAlumno
        limpiarTabla();
        List<String> als = alumnosControlador.consultaNombreAlumnos(getIdGrupo());
        cboAlumnos.setModel(new DefaultComboBoxModel(als != null && !als.isEmpty() ? als.toArray() : new String[0]));
    }//GEN-LAST:event_consultaAlumno


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cboAlumnos;
    private javax.swing.JComboBox<String> cboGrupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblResultados;
    // End of variables declaration//GEN-END:variables
}
