/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JOptionPane;

/**
 *
 * @author CAROL
 */
public class jfrmprincipal extends javax.swing.JFrame {

    /**
     * Creates new form jfrmprincipal
     */
    public jfrmprincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        menuAlumnos = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        mnuAlConsulta = new javax.swing.JMenuItem();
        mnuAlCardex = new javax.swing.JMenuItem();
        menuDocentes = new javax.swing.JMenu();
        mnuDocRegistro = new javax.swing.JMenuItem();
        mnuDocConsulta = new javax.swing.JMenuItem();
        menuMaterias = new javax.swing.JMenu();
        mnuMatRegistro = new javax.swing.JMenuItem();
        mnuMatDocentes = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        mnuRepAlumnos = new javax.swing.JMenuItem();
        mnuRepCalificaciones = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SISTEMA DE CONTROL ESCOLAR");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("COBAEZ PLANTEL 02");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("VILLA GONZALEZ ORTEGA");

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(269, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(290, Short.MAX_VALUE))
        );

        menuAlumnos.setText("Alumnos");

        jMenuItem2.setText("Registro");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroAlumno(evt);
            }
        });
        menuAlumnos.add(jMenuItem2);

        mnuAlConsulta.setText("Consulta");
        mnuAlConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirConsulta(evt);
            }
        });
        menuAlumnos.add(mnuAlConsulta);

        mnuAlCardex.setText("Cardex");
        mnuAlCardex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardexAlumnos(evt);
            }
        });
        menuAlumnos.add(mnuAlCardex);

        menu.add(menuAlumnos);

        menuDocentes.setText("Docentes");
        menuDocentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroDocentes(evt);
            }
        });

        mnuDocRegistro.setText("Registro");
        mnuDocRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroDocentes(evt);
            }
        });
        menuDocentes.add(mnuDocRegistro);

        mnuDocConsulta.setText("Consulta");
        mnuDocConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaDocentes(evt);
            }
        });
        menuDocentes.add(mnuDocConsulta);

        menu.add(menuDocentes);

        menuMaterias.setText("Materias");
        menuMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroMaterias(evt);
            }
        });

        mnuMatRegistro.setText("Registro Materias");
        mnuMatRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroMaterias(evt);
            }
        });
        menuMaterias.add(mnuMatRegistro);

        mnuMatDocentes.setText("Asignación a Docentes");
        mnuMatDocentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materiasDocentes(evt);
            }
        });
        menuMaterias.add(mnuMatDocentes);

        menu.add(menuMaterias);

        menuReportes.setText("Reportes");

        mnuRepAlumnos.setText("Alumnos");
        mnuRepAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteAlumnos(evt);
            }
        });
        menuReportes.add(mnuRepAlumnos);

        mnuRepCalificaciones.setText("Calificaciones");
        mnuRepCalificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteCalificaciones(evt);
            }
        });
        menuReportes.add(mnuRepCalificaciones);

        menu.add(menuReportes);

        menuSalir.setText("Salir");
        menuSalir.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                salir(evt);
            }
        });
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirSistema(evt);
            }
        });
        menu.add(menuSalir);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registroAlumno(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroAlumno
        FormAlumnos als = new FormAlumnos();
        jDesktopPane1.add(als);
        als.show();
    }//GEN-LAST:event_registroAlumno

    private void abrirConsulta(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirConsulta
        FormAlumnosConsulta fac = new FormAlumnosConsulta();
        jDesktopPane1.add(fac);
        fac.show();
    }//GEN-LAST:event_abrirConsulta

    private void registroDocentes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroDocentes
        FormDocentes doc = new FormDocentes();
        jDesktopPane1.add(doc);
        doc.show();
    }//GEN-LAST:event_registroDocentes

    private void consultaDocentes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaDocentes
        FormDocentesConsulta docCons = new FormDocentesConsulta();
        jDesktopPane1.add(docCons);
        docCons.show();
    }//GEN-LAST:event_consultaDocentes

    private void registroMaterias(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroMaterias
        FormMaterias mat = new FormMaterias();
        jDesktopPane1.add(mat);
        mat.show();
    }//GEN-LAST:event_registroMaterias

    private void materiasDocentes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materiasDocentes
        FormMateriasDocentes md = new FormMateriasDocentes();
        jDesktopPane1.add(md);
        md.show();
    }//GEN-LAST:event_materiasDocentes

    private void reporteAlumnos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteAlumnos
        FormReporteAlumnos ra = new FormReporteAlumnos();
        jDesktopPane1.add(ra);
        ra.show();
    }//GEN-LAST:event_reporteAlumnos

    private void reporteCalificaciones(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteCalificaciones
        FormReporteCalificaciones rc = new FormReporteCalificaciones();
        jDesktopPane1.add(rc);
        rc.show();
    }//GEN-LAST:event_reporteCalificaciones

    private void cardexAlumnos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardexAlumnos
        FormAlumnosCardex card = new FormAlumnosCardex();
        jDesktopPane1.add(card);
        card.show();
    }//GEN-LAST:event_cardexAlumnos

    private void salirSistema(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirSistema
        
    }//GEN-LAST:event_salirSistema

    private void salir(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_salir
        int dialogResult = JOptionPane.showConfirmDialog(null, "Desea salir del sistema?", 
                    "Advertencia", JOptionPane.YES_NO_OPTION);
            if (dialogResult == JOptionPane.YES_OPTION) {
                    this.dispose();
            }
    }//GEN-LAST:event_salir

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuAlumnos;
    private javax.swing.JMenu menuDocentes;
    private javax.swing.JMenu menuMaterias;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu menuSalir;
    private javax.swing.JMenuItem mnuAlCardex;
    private javax.swing.JMenuItem mnuAlConsulta;
    private javax.swing.JMenuItem mnuDocConsulta;
    private javax.swing.JMenuItem mnuDocRegistro;
    private javax.swing.JMenuItem mnuMatDocentes;
    private javax.swing.JMenuItem mnuMatRegistro;
    private javax.swing.JMenuItem mnuRepAlumnos;
    private javax.swing.JMenuItem mnuRepCalificaciones;
    // End of variables declaration//GEN-END:variables

  
      
    
}

