/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author CAROL
 */
public class jfrmprincipal extends javax.swing.JFrame {

    /**
     * Creates new form jfrmprincipal
     */
    public jfrmprincipal() {
        initComponents();
        /*menuAlumnos.setVisible(false);
        menuDocentes.setVisible(false);
        FormLogin login = new FormLogin();
        jDesktopPane1.add(login);
        login.show();*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        menu = new javax.swing.JMenuBar();
        menuAlumnos = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        mnuAlConsulta = new javax.swing.JMenuItem();
        mnuAlCardex = new javax.swing.JMenuItem();
        menuDocentes = new javax.swing.JMenu();
        mnuDocRegistro = new javax.swing.JMenuItem();
        mnuDocConsulta = new javax.swing.JMenuItem();
        menuMaterias = new javax.swing.JMenu();
        mnuMatRegistro = new javax.swing.JMenuItem();
        mnuMatDocentes = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        mnuRepAlumnos = new javax.swing.JMenuItem();
        mnuRepCalificaciones = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );

        menuAlumnos.setText("Alumnos");

        jMenuItem2.setText("Registro");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroAlumno(evt);
            }
        });
        menuAlumnos.add(jMenuItem2);

        mnuAlConsulta.setText("Consulta");
        mnuAlConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirConsulta(evt);
            }
        });
        menuAlumnos.add(mnuAlConsulta);

        mnuAlCardex.setText("Cardex");
        mnuAlCardex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardexAlumnos(evt);
            }
        });
        menuAlumnos.add(mnuAlCardex);

        menu.add(menuAlumnos);

        menuDocentes.setText("Docentes");
        menuDocentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroDocentes(evt);
            }
        });

        mnuDocRegistro.setText("Registro");
        mnuDocRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroDocentes(evt);
            }
        });
        menuDocentes.add(mnuDocRegistro);

        mnuDocConsulta.setText("Consulta");
        mnuDocConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaDocentes(evt);
            }
        });
        menuDocentes.add(mnuDocConsulta);

        menu.add(menuDocentes);

        menuMaterias.setText("Materias");
        menuMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroMaterias(evt);
            }
        });

        mnuMatRegistro.setText("Registro Materias");
        mnuMatRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroMaterias(evt);
            }
        });
        menuMaterias.add(mnuMatRegistro);

        mnuMatDocentes.setText("Asignación a Docentes");
        mnuMatDocentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materiasDocentes(evt);
            }
        });
        menuMaterias.add(mnuMatDocentes);

        menu.add(menuMaterias);

        menuReportes.setText("Reportes");

        mnuRepAlumnos.setText("Alumnos");
        mnuRepAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteAlumnos(evt);
            }
        });
        menuReportes.add(mnuRepAlumnos);

        mnuRepCalificaciones.setText("Calificaciones");
        mnuRepCalificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteCalificaciones(evt);
            }
        });
        menuReportes.add(mnuRepCalificaciones);

        menu.add(menuReportes);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registroAlumno(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroAlumno
        FormAlumnos als = new FormAlumnos();
        jDesktopPane1.add(als);
        als.show();
    }//GEN-LAST:event_registroAlumno

    private void abrirConsulta(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirConsulta
        FormAlumnosConsulta fac = new FormAlumnosConsulta();
        jDesktopPane1.add(fac);
        fac.show();
    }//GEN-LAST:event_abrirConsulta

    private void registroDocentes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroDocentes
        FormDocentes doc = new FormDocentes();
        jDesktopPane1.add(doc);
        doc.show();
    }//GEN-LAST:event_registroDocentes

    private void consultaDocentes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaDocentes
        FormDocentesConsulta docCons = new FormDocentesConsulta();
        jDesktopPane1.add(docCons);
        docCons.show();
    }//GEN-LAST:event_consultaDocentes

    private void registroMaterias(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroMaterias
        FormMaterias mat = new FormMaterias();
        jDesktopPane1.add(mat);
        mat.show();
    }//GEN-LAST:event_registroMaterias

    private void materiasDocentes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materiasDocentes
        FormMateriasDocentes md = new FormMateriasDocentes();
        jDesktopPane1.add(md);
        md.show();
    }//GEN-LAST:event_materiasDocentes

    private void reporteAlumnos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteAlumnos
        FormReporteAlumnos ra = new FormReporteAlumnos();
        jDesktopPane1.add(ra);
        ra.show();
    }//GEN-LAST:event_reporteAlumnos

    private void reporteCalificaciones(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteCalificaciones
        FormReporteCalificaciones rc = new FormReporteCalificaciones();
        jDesktopPane1.add(rc);
        rc.show();
    }//GEN-LAST:event_reporteCalificaciones

    private void cardexAlumnos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardexAlumnos
        FormAlumnosCardex card = new FormAlumnosCardex();
        jDesktopPane1.add(card);
        card.show();
    }//GEN-LAST:event_cardexAlumnos

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuAlumnos;
    private javax.swing.JMenu menuDocentes;
    private javax.swing.JMenu menuMaterias;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenuItem mnuAlCardex;
    private javax.swing.JMenuItem mnuAlConsulta;
    private javax.swing.JMenuItem mnuDocConsulta;
    private javax.swing.JMenuItem mnuDocRegistro;
    private javax.swing.JMenuItem mnuMatDocentes;
    private javax.swing.JMenuItem mnuMatRegistro;
    private javax.swing.JMenuItem mnuRepAlumnos;
    private javax.swing.JMenuItem mnuRepCalificaciones;
    // End of variables declaration//GEN-END:variables

  
      
    
}

